package modelAdministrativo.bc.vista;

import model.bc.VistaObjeto;

import modelAdministrativo.bc.AdministrativoModuloImpl;
import modelAdministrativo.bc.modulo.CodigoDefinidoUsuario;
import modelAdministrativo.bc.vista.common.CodigoDefinidoUsuarioEncabezadoView;

import oracle.jbo.VariableValueManager;
import oracle.jbo.ViewCriteria;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 23 22:31:38 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CodigoDefinidoUsuarioEncabezadoViewImpl extends VistaObjeto implements CodigoDefinidoUsuarioEncabezadoView {
    /**
     * This is the default constructor (do not remove).
     */
    public CodigoDefinidoUsuarioEncabezadoViewImpl() {
        super();
    }

    /**
     * Metodo para recargar la pantalla luego de una cancelacion del un detalla en el detalle-template
     *
     * @param id
     */
    public void ejecutarIdEntidad(Integer id) {
        ViewCriteria vc =
            this.getViewCriteriaManager().getViewCriteria("CodigoDefinidoUsuarioEncabezadoViewCriteriaRecargarDetalle");
        VariableValueManager vvm = vc.ensureVariableManager();
        vvm.setVariableValue("v_idCodigoDefinidoUsuario", id);
        this.applyViewCriteria(vc, false);
        this.executeQuery();
        this.setApplyViewCriteriaName(null);
    }

    /**
     * Metodo para enviar al inicio.
     *
     */
    public void cduArriba() {
      CodigoDefinidoUsuario.unMovimiento((AdministrativoModuloImpl) this.getApplicationModule(),
                                                  ((CodigoDefinidoUsuarioEncabezadoViewRowImpl) this.getCurrentRow())
                                                  .getIdCodigoDefinidoUsuario(), true);
        this.executeQuery();
    }

    /**
     * Metodo para enviar al inicio.
     *
     */
    public void cduAbajo() {
      CodigoDefinidoUsuario.unMovimiento((AdministrativoModuloImpl) this.getApplicationModule(),
                                                  ((CodigoDefinidoUsuarioEncabezadoViewRowImpl) this.getCurrentRow())
                                                  .getIdCodigoDefinidoUsuario(), false);
        this.executeQuery();
    }

    /**
     * Metodo para enviar al inicio.
     *     
     */
    public void cduPrimero() {
        CodigoDefinidoUsuario.ejecutarExtremos((AdministrativoModuloImpl) this.getApplicationModule(),
                                                      ((CodigoDefinidoUsuarioEncabezadoViewRowImpl) this.getCurrentRow()).getIdCodigoDefinidoUsuario(), 
                                                      -1);
        this.executeQuery();
    }

    /**
     * Metodo para enviar al fondo.
     *
     */
    public void cduUltimo() {
        CodigoDefinidoUsuario.ejecutarExtremos((AdministrativoModuloImpl) this.getApplicationModule(),
                                                      ((CodigoDefinidoUsuarioEncabezadoViewRowImpl) this.getCurrentRow()).getIdCodigoDefinidoUsuario(),
                                                      1000);        
        this.executeQuery();
    }
}
