package modelAdministrativo.bc.vista;

import java.sql.Timestamp;

import modelAdministrativo.bc.entidad.CodigoDefinidoUsuarioImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 29 12:10:14 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CodigoDefinidoUsuarioEncabezadoViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_CODIGODEFINIDOUSUARIO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdCodigoDefinidoUsuario,
        IdModulo,
        Grupo,
        CodigoTexto,
        CodigoNumero,
        Nombre,
        Descripcion,
        Orden,
        Estado,
        Usuario,
        UsuarioFecha,
        UsuarioPrograma,
        CodigoDefinidoUsuarioDetalleView,
        CodigoDefinidoUsuarioViewLOV1,
        ModuloView1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDCODIGODEFINIDOUSUARIO = AttributesEnum.IdCodigoDefinidoUsuario.index();
    public static final int IDMODULO = AttributesEnum.IdModulo.index();
    public static final int GRUPO = AttributesEnum.Grupo.index();
    public static final int CODIGOTEXTO = AttributesEnum.CodigoTexto.index();
    public static final int CODIGONUMERO = AttributesEnum.CodigoNumero.index();
    public static final int NOMBRE = AttributesEnum.Nombre.index();
    public static final int DESCRIPCION = AttributesEnum.Descripcion.index();
    public static final int ORDEN = AttributesEnum.Orden.index();
    public static final int ESTADO = AttributesEnum.Estado.index();
    public static final int USUARIO = AttributesEnum.Usuario.index();
    public static final int USUARIOFECHA = AttributesEnum.UsuarioFecha.index();
    public static final int USUARIOPROGRAMA = AttributesEnum.UsuarioPrograma.index();
    public static final int CODIGODEFINIDOUSUARIODETALLEVIEW = AttributesEnum.CodigoDefinidoUsuarioDetalleView.index();
    public static final int CODIGODEFINIDOUSUARIOVIEWLOV1 = AttributesEnum.CodigoDefinidoUsuarioViewLOV1.index();
    public static final int MODULOVIEW1 = AttributesEnum.ModuloView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CodigoDefinidoUsuarioEncabezadoViewRowImpl() {
    }

    /**
     * Gets CodigoDefinidoUsuario entity object.
     * @return the CodigoDefinidoUsuario
     */
    public CodigoDefinidoUsuarioImpl getCodigoDefinidoUsuario() {
        return (CodigoDefinidoUsuarioImpl) getEntity(ENTITY_CODIGODEFINIDOUSUARIO);
    }

    /**
     * Gets the attribute value for id_codigo_definido_usuario using the alias name IdCodigoDefinidoUsuario.
     * @return the id_codigo_definido_usuario
     */
    public Integer getIdCodigoDefinidoUsuario() {
        return (Integer) getAttributeInternal(IDCODIGODEFINIDOUSUARIO);
    }

    /**
     * Sets <code>value</code> as attribute value for id_codigo_definido_usuario using the alias name IdCodigoDefinidoUsuario.
     * @param value value to set the id_codigo_definido_usuario
     */
    public void setIdCodigoDefinidoUsuario(Integer value) {
        setAttributeInternal(IDCODIGODEFINIDOUSUARIO, value);
    }

    /**
     * Gets the attribute value for id_modulo using the alias name IdModulo.
     * @return the id_modulo
     */
    public Integer getIdModulo() {
        return (Integer) getAttributeInternal(IDMODULO);
    }

    /**
     * Sets <code>value</code> as attribute value for id_modulo using the alias name IdModulo.
     * @param value value to set the id_modulo
     */
    public void setIdModulo(Integer value) {
        setAttributeInternal(IDMODULO, value);
    }

    /**
     * Gets the attribute value for grupo using the alias name Grupo.
     * @return the grupo
     */
    public String getGrupo() {
        return (String) getAttributeInternal(GRUPO);
    }

    /**
     * Sets <code>value</code> as attribute value for grupo using the alias name Grupo.
     * @param value value to set the grupo
     */
    public void setGrupo(String value) {
        setAttributeInternal(GRUPO, value);
    }

    /**
     * Gets the attribute value for codigo_texto using the alias name CodigoTexto.
     * @return the codigo_texto
     */
    public String getCodigoTexto() {
        return (String) getAttributeInternal(CODIGOTEXTO);
    }

    /**
     * Sets <code>value</code> as attribute value for codigo_texto using the alias name CodigoTexto.
     * @param value value to set the codigo_texto
     */
    public void setCodigoTexto(String value) {
        setAttributeInternal(CODIGOTEXTO, value);
    }

    /**
     * Gets the attribute value for codigo_numero using the alias name CodigoNumero.
     * @return the codigo_numero
     */
    public Integer getCodigoNumero() {
        return (Integer) getAttributeInternal(CODIGONUMERO);
    }

    /**
     * Sets <code>value</code> as attribute value for codigo_numero using the alias name CodigoNumero.
     * @param value value to set the codigo_numero
     */
    public void setCodigoNumero(Integer value) {
        setAttributeInternal(CODIGONUMERO, value);
    }

    /**
     * Gets the attribute value for nombre using the alias name Nombre.
     * @return the nombre
     */
    public String getNombre() {
        return (String) getAttributeInternal(NOMBRE);
    }

    /**
     * Sets <code>value</code> as attribute value for nombre using the alias name Nombre.
     * @param value value to set the nombre
     */
    public void setNombre(String value) {
        setAttributeInternal(NOMBRE, value);
    }

    /**
     * Gets the attribute value for descripcion using the alias name Descripcion.
     * @return the descripcion
     */
    public String getDescripcion() {
        return (String) getAttributeInternal(DESCRIPCION);
    }

    /**
     * Sets <code>value</code> as attribute value for descripcion using the alias name Descripcion.
     * @param value value to set the descripcion
     */
    public void setDescripcion(String value) {
        setAttributeInternal(DESCRIPCION, value);
    }

    /**
     * Gets the attribute value for orden using the alias name Orden.
     * @return the orden
     */
    public Integer getOrden() {
        return (Integer) getAttributeInternal(ORDEN);
    }

    /**
     * Sets <code>value</code> as attribute value for orden using the alias name Orden.
     * @param value value to set the orden
     */
    public void setOrden(Integer value) {
        setAttributeInternal(ORDEN, value);
    }

    /**
     * Gets the attribute value for estado using the alias name Estado.
     * @return the estado
     */
    public String getEstado() {
        return (String) getAttributeInternal(ESTADO);
    }

    /**
     * Sets <code>value</code> as attribute value for estado using the alias name Estado.
     * @param value value to set the estado
     */
    public void setEstado(String value) {
        setAttributeInternal(ESTADO, value);
    }

    /**
     * Gets the attribute value for usuario using the alias name Usuario.
     * @return the usuario
     */
    public String getUsuario() {
        return (String) getAttributeInternal(USUARIO);
    }

    /**
     * Sets <code>value</code> as attribute value for usuario using the alias name Usuario.
     * @param value value to set the usuario
     */
    public void setUsuario(String value) {
        setAttributeInternal(USUARIO, value);
    }

    /**
     * Gets the attribute value for usuario_fecha using the alias name UsuarioFecha.
     * @return the usuario_fecha
     */
    public Timestamp getUsuarioFecha() {
        return (Timestamp) getAttributeInternal(USUARIOFECHA);
    }

    /**
     * Sets <code>value</code> as attribute value for usuario_fecha using the alias name UsuarioFecha.
     * @param value value to set the usuario_fecha
     */
    public void setUsuarioFecha(Timestamp value) {
        setAttributeInternal(USUARIOFECHA, value);
    }

    /**
     * Gets the attribute value for usuario_programa using the alias name UsuarioPrograma.
     * @return the usuario_programa
     */
    public String getUsuarioPrograma() {
        return (String) getAttributeInternal(USUARIOPROGRAMA);
    }

    /**
     * Sets <code>value</code> as attribute value for usuario_programa using the alias name UsuarioPrograma.
     * @param value value to set the usuario_programa
     */
    public void setUsuarioPrograma(String value) {
        setAttributeInternal(USUARIOPROGRAMA, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CodigoDefinidoUsuarioDetalleView.
     */
    public RowIterator getCodigoDefinidoUsuarioDetalleView() {
        return (RowIterator) getAttributeInternal(CODIGODEFINIDOUSUARIODETALLEVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CodigoDefinidoUsuarioViewLOV1.
     */
    public RowSet getCodigoDefinidoUsuarioViewLOV1() {
        return (RowSet) getAttributeInternal(CODIGODEFINIDOUSUARIOVIEWLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ModuloView1.
     */
    public RowSet getModuloView1() {
        return (RowSet) getAttributeInternal(MODULOVIEW1);
    }
}

