package modelAdministrativo.bc.vista;

import modelAdministrativo.bc.AdministrativoModuloImpl;
import modelAdministrativo.bc.modulo.CodigoDefinidoUsuario;
import modelAdministrativo.bc.vista.common.CodigoDefinidoUsuarioDetalleView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 29 12:15:54 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CodigoDefinidoUsuarioDetalleViewImpl extends ViewObjectImpl implements CodigoDefinidoUsuarioDetalleView {
    /**
     * This is the default constructor (do not remove).
     */
    public CodigoDefinidoUsuarioDetalleViewImpl() {
        super();
    }

    /**
     * Metodo para enviar al inicio.
     *
     */
    public void cduArriba() {
        CodigoDefinidoUsuario.unMovimiento((AdministrativoModuloImpl) this.getApplicationModule(),
                                           ((CodigoDefinidoUsuarioDetalleViewRowImpl) this.getCurrentRow())
                                           .getIdCodigoDefinidoUsuario(), true);
        this.executeQuery();
    }

    /**
     * Metodo para enviar al inicio.
     *
     */
    public void cduAbajo() {
        CodigoDefinidoUsuario.unMovimiento((AdministrativoModuloImpl) this.getApplicationModule(),
                                           ((CodigoDefinidoUsuarioDetalleViewRowImpl) this.getCurrentRow())
                                           .getIdCodigoDefinidoUsuario(), false);
        this.executeQuery();
    }

    /**
     * Metodo para enviar al inicio.
     *
     */
    public void cduPrimero() {
        CodigoDefinidoUsuario.ejecutarExtremos((AdministrativoModuloImpl) this.getApplicationModule(),
                                               ((CodigoDefinidoUsuarioDetalleViewRowImpl) this.getCurrentRow())
                                               .getIdCodigoDefinidoUsuario(), -1);
        this.executeQuery();
    }

    /**
     * Metodo para enviar al fondo.
     *
     */
    public void cduUltimo() {
        CodigoDefinidoUsuario.ejecutarExtremos((AdministrativoModuloImpl) this.getApplicationModule(),
                                               ((CodigoDefinidoUsuarioDetalleViewRowImpl) this.getCurrentRow())
                                               .getIdCodigoDefinidoUsuario(), 1000);
        this.executeQuery();
    }
}
