package modelAdministrativo.bc.vista;

import model.bc.VistaObjeto;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 01 12:20:19 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InformacionViewImpl extends VistaObjeto {
    /**
     * This is the default constructor (do not remove).
     */
    public InformacionViewImpl() {
        super();
    }
}

