package modelAdministrativo.bc.vista;

import java.sql.Timestamp;

import modelAdministrativo.bc.entidad.MenuImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 08 22:31:31 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MenuViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_MENU = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdMenu,
        IdModulo,
        Tipo,
        Indice,
        Nombre,
        TaskFlow,
        Estado,
        Orden,
        Usuario,
        UsuarioFecha,
        UsuarioPrograma,
        PermisoView,
        CodigoDefinidoUsuarioViewLOV1,
        CodigoDefinidoUsuarioViewLOV2,
        ModuloView1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDMENU = AttributesEnum.IdMenu.index();
    public static final int IDMODULO = AttributesEnum.IdModulo.index();
    public static final int TIPO = AttributesEnum.Tipo.index();
    public static final int INDICE = AttributesEnum.Indice.index();
    public static final int NOMBRE = AttributesEnum.Nombre.index();
    public static final int TASKFLOW = AttributesEnum.TaskFlow.index();
    public static final int ESTADO = AttributesEnum.Estado.index();
    public static final int ORDEN = AttributesEnum.Orden.index();
    public static final int USUARIO = AttributesEnum.Usuario.index();
    public static final int USUARIOFECHA = AttributesEnum.UsuarioFecha.index();
    public static final int USUARIOPROGRAMA = AttributesEnum.UsuarioPrograma.index();
    public static final int PERMISOVIEW = AttributesEnum.PermisoView.index();
    public static final int CODIGODEFINIDOUSUARIOVIEWLOV1 = AttributesEnum.CodigoDefinidoUsuarioViewLOV1.index();
    public static final int CODIGODEFINIDOUSUARIOVIEWLOV2 = AttributesEnum.CodigoDefinidoUsuarioViewLOV2.index();
    public static final int MODULOVIEW1 = AttributesEnum.ModuloView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MenuViewRowImpl() {
    }

    /**
     * Gets Menu entity object.
     * @return the Menu
     */
    public MenuImpl getMenu() {
        return (MenuImpl) getEntity(ENTITY_MENU);
    }

    /**
     * Gets the attribute value for id_menu using the alias name IdMenu.
     * @return the id_menu
     */
    public Integer getIdMenu() {
        return (Integer) getAttributeInternal(IDMENU);
    }

    /**
     * Sets <code>value</code> as attribute value for id_menu using the alias name IdMenu.
     * @param value value to set the id_menu
     */
    public void setIdMenu(Integer value) {
        setAttributeInternal(IDMENU, value);
    }

    /**
     * Gets the attribute value for id_modulo using the alias name IdModulo.
     * @return the id_modulo
     */
    public Integer getIdModulo() {
        return (Integer) getAttributeInternal(IDMODULO);
    }

    /**
     * Sets <code>value</code> as attribute value for id_modulo using the alias name IdModulo.
     * @param value value to set the id_modulo
     */
    public void setIdModulo(Integer value) {
        setAttributeInternal(IDMODULO, value);
    }

    /**
     * Gets the attribute value for tipo using the alias name Tipo.
     * @return the tipo
     */
    public String getTipo() {
        return (String) getAttributeInternal(TIPO);
    }

    /**
     * Sets <code>value</code> as attribute value for tipo using the alias name Tipo.
     * @param value value to set the tipo
     */
    public void setTipo(String value) {
        setAttributeInternal(TIPO, value);
    }

    /**
     * Gets the attribute value for indice using the alias name Indice.
     * @return the indice
     */
    public String getIndice() {
        return (String) getAttributeInternal(INDICE);
    }

    /**
     * Sets <code>value</code> as attribute value for indice using the alias name Indice.
     * @param value value to set the indice
     */
    public void setIndice(String value) {
        setAttributeInternal(INDICE, value);
    }

    /**
     * Gets the attribute value for nombre using the alias name Nombre.
     * @return the nombre
     */
    public String getNombre() {
        return (String) getAttributeInternal(NOMBRE);
    }

    /**
     * Sets <code>value</code> as attribute value for nombre using the alias name Nombre.
     * @param value value to set the nombre
     */
    public void setNombre(String value) {
        setAttributeInternal(NOMBRE, value);
    }

    /**
     * Gets the attribute value for task_flow using the alias name TaskFlow.
     * @return the task_flow
     */
    public String getTaskFlow() {
        return (String) getAttributeInternal(TASKFLOW);
    }

    /**
     * Sets <code>value</code> as attribute value for task_flow using the alias name TaskFlow.
     * @param value value to set the task_flow
     */
    public void setTaskFlow(String value) {
        setAttributeInternal(TASKFLOW, value);
    }

    /**
     * Gets the attribute value for estado using the alias name Estado.
     * @return the estado
     */
    public String getEstado() {
        return (String) getAttributeInternal(ESTADO);
    }

    /**
     * Sets <code>value</code> as attribute value for estado using the alias name Estado.
     * @param value value to set the estado
     */
    public void setEstado(String value) {
        setAttributeInternal(ESTADO, value);
    }

    /**
     * Gets the attribute value for orden using the alias name Orden.
     * @return the orden
     */
    public Integer getOrden() {
        return (Integer) getAttributeInternal(ORDEN);
    }

    /**
     * Sets <code>value</code> as attribute value for orden using the alias name Orden.
     * @param value value to set the orden
     */
    public void setOrden(Integer value) {
        setAttributeInternal(ORDEN, value);
    }

    /**
     * Gets the attribute value for usuario using the alias name Usuario.
     * @return the usuario
     */
    public String getUsuario() {
        return (String) getAttributeInternal(USUARIO);
    }

    /**
     * Sets <code>value</code> as attribute value for usuario using the alias name Usuario.
     * @param value value to set the usuario
     */
    public void setUsuario(String value) {
        setAttributeInternal(USUARIO, value);
    }

    /**
     * Gets the attribute value for usuario_fecha using the alias name UsuarioFecha.
     * @return the usuario_fecha
     */
    public Timestamp getUsuarioFecha() {
        return (Timestamp) getAttributeInternal(USUARIOFECHA);
    }

    /**
     * Sets <code>value</code> as attribute value for usuario_fecha using the alias name UsuarioFecha.
     * @param value value to set the usuario_fecha
     */
    public void setUsuarioFecha(Timestamp value) {
        setAttributeInternal(USUARIOFECHA, value);
    }

    /**
     * Gets the attribute value for usuario_programa using the alias name UsuarioPrograma.
     * @return the usuario_programa
     */
    public String getUsuarioPrograma() {
        return (String) getAttributeInternal(USUARIOPROGRAMA);
    }

    /**
     * Sets <code>value</code> as attribute value for usuario_programa using the alias name UsuarioPrograma.
     * @param value value to set the usuario_programa
     */
    public void setUsuarioPrograma(String value) {
        setAttributeInternal(USUARIOPROGRAMA, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PermisoView.
     */
    public RowIterator getPermisoView() {
        return (RowIterator) getAttributeInternal(PERMISOVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CodigoDefinidoUsuarioViewLOV1.
     */
    public RowSet getCodigoDefinidoUsuarioViewLOV1() {
        return (RowSet) getAttributeInternal(CODIGODEFINIDOUSUARIOVIEWLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CodigoDefinidoUsuarioViewLOV2.
     */
    public RowSet getCodigoDefinidoUsuarioViewLOV2() {
        return (RowSet) getAttributeInternal(CODIGODEFINIDOUSUARIOVIEWLOV2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ModuloView1.
     */
    public RowSet getModuloView1() {
        return (RowSet) getAttributeInternal(MODULOVIEW1);
    }
}

