package modelAdministrativo.bc.vista;

import model.bc.VistaObjeto;

import modelAdministrativo.bc.AdministrativoModuloImpl;
import modelAdministrativo.bc.modulo.Menu;
import modelAdministrativo.bc.vista.common.MenuView;

import oracle.jbo.VariableValueManager;
import oracle.jbo.ViewCriteria;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 08 11:48:52 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MenuViewImpl extends VistaObjeto implements MenuView {
    /**
     * This is the default constructor (do not remove).
     */
    public MenuViewImpl() {
        super();
    }
    
    
    /**
     * Metodo para recargar la pantalla luego de una cancelacion del un detalla en el detalle-template
     *
     * @param id
     */
    public void ejecutarIdEntidad(Integer id) {
        ViewCriteria vc = this.getViewCriteriaManager().getViewCriteria("MenuViewCriteriaRecargarDetalle");
        VariableValueManager vvm = vc.ensureVariableManager();
        vvm.setVariableValue("v_idMenu", id);
        this.applyViewCriteria(vc, false);
        this.executeQuery();
        this.setApplyViewCriteriaName(null);        
    }    
    
    /**
     * Metodo para enviar al inicio.
     *
     */
    public void cduArriba() {
      Menu.unMovimiento((AdministrativoModuloImpl) this.getApplicationModule(),
                                                  ((MenuViewRowImpl) this.getCurrentRow())
                                                  .getIdMenu(), true);
        this.executeQuery();
    }

    /**
     * Metodo para enviar al inicio.
     *
     */
    public void cduAbajo() {
      Menu.unMovimiento((AdministrativoModuloImpl) this.getApplicationModule(),
                                                  ((MenuViewRowImpl) this.getCurrentRow())
                                                  .getIdMenu(), false);
        this.executeQuery();
    }

    /**
     * Metodo para enviar al inicio.
     *     
     */
    public void cduPrimero() {
        Menu.ejecutarExtremos((AdministrativoModuloImpl) this.getApplicationModule(),
                                                      ((MenuViewRowImpl) this.getCurrentRow()).getIdMenu(), 
                                                      -1);
        this.executeQuery();
    }

    /**
     * Metodo para enviar al fondo.
     *
     */
    public void cduUltimo() {
        Menu.ejecutarExtremos((AdministrativoModuloImpl) this.getApplicationModule(),
                                                      ((MenuViewRowImpl) this.getCurrentRow()).getIdMenu(),
                                                      1000);        
        this.executeQuery();
    }
}

