package modelAdministrativo.bc.vista;

import model.bc.VistaObjeto;

import modelAdministrativo.bc.vista.common.ModuloView;

import oracle.jbo.VariableValueManager;
import oracle.jbo.ViewCriteria;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 24 15:18:13 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ModuloViewImpl extends VistaObjeto implements ModuloView {
    /**
     * This is the default constructor (do not remove).
     */
    public ModuloViewImpl() {
        super();
    }
    
    /**
     * Metodo para recargar la pantalla luego de una cancelacion del un detalla en el detalle-template
     *
     * @param id
     */
    public void ejecutarIdEntidad(Integer id) {
        ViewCriteria vc = this.getViewCriteriaManager().getViewCriteria("ModuloViewCriteriaRecargarDetalle");
                                                                        
        VariableValueManager vvm = vc.ensureVariableManager();
        vvm.setVariableValue("v_idModulo", id);
        this.applyViewCriteria(vc, false);
        this.executeQuery();
        this.setApplyViewCriteriaName(null);
    }
}

