package modelAdministrativo.bc.vista;

import model.bc.VistaObjeto;

import modelAdministrativo.bc.vista.common.RolView;

import oracle.jbo.VariableValueManager;
import oracle.jbo.ViewCriteria;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 24 15:17:18 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RolViewImpl extends VistaObjeto implements RolView {
    /**
     * This is the default constructor (do not remove).
     */
    public RolViewImpl() {
        super();
    }

    /**
     * Metodo para recargar la pantalla luego de una cancelacion del un detalla en el detalle-template
     *
     * @param id
     */
    public void ejecutarIdEntidad(Integer id) {
        ViewCriteria vc = this.getViewCriteriaManager().getViewCriteria("RolViewCriteriaRecargarDetalle");
        VariableValueManager vvm = vc.ensureVariableManager();
        vvm.setVariableValue("v_idRol", id);
        this.applyViewCriteria(vc, false);
        this.executeQuery();
        this.setApplyViewCriteriaName(null);
    }
}