package modelAdministrativo.bc.vista;
  
  import model.bc.VistaObjeto;

  import modelAdministrativo.bc.vista.common.UsuarioView;

  import oracle.jbo.VariableValueManager;
  import oracle.jbo.ViewCriteria;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 24 15:12:41 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UsuarioViewImpl extends VistaObjeto implements UsuarioView {
    /**
     * This is the default constructor (do not remove).
     */
    public UsuarioViewImpl() {
        super();
    }    
  
    /**
     * Metodo para recargar la pantalla luego de una cancelacion del un detalla en el detalle-template
     *
     * @param id
     */
    public void ejecutarIdEntidad(Integer id) {
        ViewCriteria vc =
            this.getViewCriteriaManager().getViewCriteria("UsuarioViewCriteriaRecargarDetalle");
      VariableValueManager vvm = vc.ensureVariableManager();
      vvm.setVariableValue("v_idUsuario", id);
        this.applyViewCriteria(vc, false);
        this.executeQuery();
        this.setApplyViewCriteriaName(null);
    }
}