package modelAuditoria.bc;


import java.util.List;

import model.bc.ModuloImpl;

import modelAuditoria.bc.modulo.Acceso;
import modelAuditoria.bc.modulo.Auditoria;
import modelAuditoria.bc.modulo.Direccion;
import modelAuditoria.bc.modulo.estructura.Parametro;
import modelAuditoria.bc.vistaNoDML.AccesoTokenViewNoDMLImpl;

import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 13 19:46:10 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AuditoriaModuloImpl extends ModuloImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AuditoriaModuloImpl() {
        super();
        setNombreBundle("modelAuditoria.ModelAuditoriaBundle");        
    }

    /**
     * Metodo para crear la direccion.
     *
     * @param elemento
     * @param direccion
     * @param navegadorDispositivo
     * @param usuarioPrograma
     * @return
     */
    public int auditoria_crearDireccion(String elemento, String direccion, String navegadorDispositivo, String usuario, String usuarioPrograma) {
        return Direccion.crearDireccion(this, elemento, direccion, navegadorDispositivo, usuario ,usuarioPrograma);        
    }
    
    /**
     * Metodo para crear Acceso.
     *
     * @param nombre
     * @param token
     * @param tokenApi
     * @param usuarioPrograma
     * @return
     */
    public int auditoria_crearAcceso( String nombre, String token, String tokenApi, String usuarioPrograma){            
        return Acceso.crearAcceso(this, nombre, token, tokenApi, usuarioPrograma);    
    }


    /**
     * Metodo para crear Auditoria.
     *
     * @param nombre
     * @param elemento
     * @param contenidoExtra
     * @param usuarioPrograma
     * @return
     */
    public int auditoria_crearAuditoria(String nombre, String elemento, String contenidoExtra, String usuarioPrograma) {
        return Auditoria.crearAuditoria(this, nombre, elemento, contenidoExtra, usuarioPrograma);
    }

    /**
     * Metodo para crear el parametro.
     *
     * @param idAuditoria
     * @param parametro
     * @return
     */
    public boolean auditoria_crearAuditoriaParametros(int idAuditoria, List<Parametro> parametro) {
        return Auditoria.crearAuditoriaParametros(this, idAuditoria, parametro);
    }


    /**
     * Metodo para crear el Evento de Auditoria.
     *
     * @param idAuditoria
     * @param descripcion
     * @param tipo
     * @param orden
     * @return
     */
    public boolean auditoria_crearAuditoriaEvento(int idAuditoria, String descripcion, String tipo, int orden) {
        return Auditoria.crearAuditoriaEvento(this, idAuditoria, descripcion, tipo, orden);
    }

    /**
     * Container's getter for AuditoriaView1.
     * @return AuditoriaView1
     */
    public ViewObjectImpl getAuditoria_AuditoriaView1() {
        return (ViewObjectImpl) findViewObject("Auditoria_AuditoriaView1");
    }

    /**
     * Container's getter for AuditoriaEventoView1.
     * @return AuditoriaEventoView1
     */
    public ViewObjectImpl getAuditoria_AuditoriaEventoView1() {
        return (ViewObjectImpl) findViewObject("Auditoria_AuditoriaEventoView1");
    }

    /**
     * Container's getter for AuditoriaParametroView1.
     * @return AuditoriaParametroView1
     */
    public ViewObjectImpl getAuditoria_AuditoriaParametroView1() {
        return (ViewObjectImpl) findViewObject("Auditoria_AuditoriaParametroView1");
    }


    /**
     * Container's getter for DireccionView1.
     * @return DireccionView1
     */
    public ViewObjectImpl getAuditoria_DireccionView1() {
        return (ViewObjectImpl) findViewObject("Auditoria_DireccionView1");
    }

    /**
     * Container's getter for InformacionView1.
     * @return InformacionView1
     */
    public ViewObjectImpl getAuditoria_InformacionView1() {
        return (ViewObjectImpl) findViewObject("Auditoria_InformacionView1");
    }

    /**
     * Container's getter for AuditoriaEventoFkLink1.
     * @return AuditoriaEventoFkLink1
     */
    public ViewLinkImpl getAuditoriaEventoFkLink1() {
        return (ViewLinkImpl) findViewLink("AuditoriaEventoFkLink1");
    }

    /**
     * Container's getter for AuditoriaParametroFkLink1.
     * @return AuditoriaParametroFkLink1
     */
    public ViewLinkImpl getAuditoriaParametroFkLink1() {
        return (ViewLinkImpl) findViewLink("AuditoriaParametroFkLink1");
    }

    /**
     * Container's getter for Auditoria_AccesoView1.
     * @return Auditoria_AccesoView1
     */
    public ViewObjectImpl getAuditoria_AccesoView1() {
        return (ViewObjectImpl) findViewObject("Auditoria_AccesoView1");
    }

    /**
     * Container's getter for AccesoTokenViewNoDML1.
     * @return AccesoTokenViewNoDML1
     */
    public AccesoTokenViewNoDMLImpl getAuditoria_AccesoTokenViewNoDML1() {
        return (AccesoTokenViewNoDMLImpl) findViewObject("Auditoria_AccesoTokenViewNoDML1");
    }

}

