package model.bc.vista;

import model.bc.VistaObjeto;


import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 19 22:54:39 ECT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GrupoViewImpl extends VistaObjeto {
    /**
     * This is the default constructor (do not remove).
     */
    public GrupoViewImpl() {
    }

    
}

