package model.bc.entidad;

import model.bc.Entidad;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 23 19:09:23 ECT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
@SuppressWarnings("oracle.jdeveloper.java.semantic-warning")
public class ArchivoEventoImpl extends Entidad {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdArchivoEvento,
        IdArchivo,
        Informacion,
        Tipo,
        Usuario,
        UsuarioFecha,
        UsuarioPrograma,
        Archivo;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDARCHIVOEVENTO = AttributesEnum.IdArchivoEvento.index();
    public static final int IDARCHIVO = AttributesEnum.IdArchivo.index();
    public static final int INFORMACION = AttributesEnum.Informacion.index();
    public static final int TIPO = AttributesEnum.Tipo.index();
    public static final int USUARIO = AttributesEnum.Usuario.index();
    public static final int USUARIOFECHA = AttributesEnum.UsuarioFecha.index();
    public static final int USUARIOPROGRAMA = AttributesEnum.UsuarioPrograma.index();
    public static final int ARCHIVO = AttributesEnum.Archivo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ArchivoEventoImpl() {
        super();
    }

    /**
     * @param idArchivoEvento key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer idArchivoEvento) {
        return new Key(new Object[] { idArchivoEvento });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.bc.entidad.ArchivoEvento");
    }


    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);

        if (operation == DML_INSERT) {
            setAttribute(IDARCHIVOEVENTO, getUltimoId());
        }
    }
}

