package model.bc.entidad;

import model.bc.Entidad;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 23 18:45:45 ECT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
@SuppressWarnings("oracle.jdeveloper.java.semantic-warning")
public class ArchivoImpl extends Entidad {
    /**
     * Add entity remove logic in this method.
     */
    public void remove() {

        setAttribute(ESTADO, "X");

        super.remove();
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO
     * NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdArchivo,
        IdGrupo,
        NombreRamdon,
        Nombre,
        Extension,
        Largo,
        PathRelativo,
        Estado,
        Usuario,
        UsuarioFecha,
        UsuarioPrograma,
        Grupo,
        ArchivoEvento;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDARCHIVO = AttributesEnum.IdArchivo.index();
    public static final int IDGRUPO = AttributesEnum.IdGrupo.index();
    public static final int NOMBRERAMDON = AttributesEnum.NombreRamdon.index();
    public static final int NOMBRE = AttributesEnum.Nombre.index();
    public static final int EXTENSION = AttributesEnum.Extension.index();
    public static final int LARGO = AttributesEnum.Largo.index();
    public static final int PATHRELATIVO = AttributesEnum.PathRelativo.index();
    public static final int ESTADO = AttributesEnum.Estado.index();
    public static final int USUARIO = AttributesEnum.Usuario.index();
    public static final int USUARIOFECHA = AttributesEnum.UsuarioFecha.index();
    public static final int USUARIOPROGRAMA = AttributesEnum.UsuarioPrograma.index();
    public static final int GRUPO = AttributesEnum.Grupo.index();
    public static final int ARCHIVOEVENTO = AttributesEnum.ArchivoEvento.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ArchivoImpl() {
        super();
    }

    /**
     * @param idArchivo key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer idArchivo) {
        return new Key(new Object[] { idArchivo });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.bc.entidad.Archivo");
    }


    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * 
     * @param operation the operation type
     * @param e         the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_DELETE) {
            operation = DML_UPDATE;
        }

        super.doDML(operation, e);

        if (operation == DML_INSERT) {
            setAttribute(IDARCHIVO, getUltimoId());
        }
    }
}
