package modelAuditoria.bc.entidad;

import java.sql.Timestamp;

import model.bc.Entidad;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 10 20:33:34 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AuditoriaImpl extends Entidad {
    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
        //Id refresh
        if (operation == DML_INSERT)
            setAttribute(IDAUDITORIA, getUltimoId());        
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdAuditoria,
        Nombre,
        Valor01,
        Valor02,
        Usuario,
        UsuarioFecha,
        UsuarioPrograma,
        Elemento,
        AuditoriaEvento,
        AuditoriaParametro;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDAUDITORIA = AttributesEnum.IdAuditoria.index();
    public static final int NOMBRE = AttributesEnum.Nombre.index();
    public static final int VALOR01 = AttributesEnum.Valor01.index();
    public static final int VALOR02 = AttributesEnum.Valor02.index();
    public static final int USUARIO = AttributesEnum.Usuario.index();
    public static final int USUARIOFECHA = AttributesEnum.UsuarioFecha.index();
    public static final int USUARIOPROGRAMA = AttributesEnum.UsuarioPrograma.index();
    public static final int ELEMENTO = AttributesEnum.Elemento.index();
    public static final int AUDITORIAEVENTO = AttributesEnum.AuditoriaEvento.index();
    public static final int AUDITORIAPARAMETRO = AttributesEnum.AuditoriaParametro.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AuditoriaImpl() {
        super();
    }

    /**
     * @param idAuditoria key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer idAuditoria) {
        return new Key(new Object[] { idAuditoria });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("modelAuditoria.bc.entidad.Auditoria");
    }


}

