package modelAuditoria.bc.entidad;

import model.bc.Entidad;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 10 20:34:23 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AuditoriaParametroImpl extends Entidad {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdAuditoriaParametro,
        IdAuditoria,
        Nombre,
        Direccion,
        Valor,
        Auditoria;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDAUDITORIAPARAMETRO = AttributesEnum.IdAuditoriaParametro.index();
    public static final int IDAUDITORIA = AttributesEnum.IdAuditoria.index();
    public static final int NOMBRE = AttributesEnum.Nombre.index();
    public static final int DIRECCION = AttributesEnum.Direccion.index();
    public static final int VALOR = AttributesEnum.Valor.index();
    public static final int AUDITORIA = AttributesEnum.Auditoria.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AuditoriaParametroImpl() {
        super();
    }

    /**
     * @param idAuditoriaParametro key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer idAuditoriaParametro) {
        return new Key(new Object[] { idAuditoriaParametro });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("modelAuditoria.bc.entidad.AuditoriaParametro");
    }


    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
        //Id refresh
        if (operation == DML_INSERT)
            setAttribute(IDAUDITORIAPARAMETRO, getUltimoId());        
    }
}

