package modelAdministrativo.bc.entidad;

import model.bc.Entidad;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 17 18:17:03 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CodigoDefinidoUsuarioImpl extends Entidad {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdCodigoDefinidoUsuario,
        IdModulo,
        Grupo,
        CodigoTexto,
        CodigoNumero,
        Nombre,
        Descripcion,
        Orden,
        Estado,
        Usuario,
        UsuarioFecha,
        UsuarioPrograma,
        Modulo,
        CodigoTextoCodigoDefinidoUsuario,
        GrupoCodigoDefinidoUsuario;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDCODIGODEFINIDOUSUARIO = AttributesEnum.IdCodigoDefinidoUsuario.index();
    public static final int IDMODULO = AttributesEnum.IdModulo.index();
    public static final int GRUPO = AttributesEnum.Grupo.index();
    public static final int CODIGOTEXTO = AttributesEnum.CodigoTexto.index();
    public static final int CODIGONUMERO = AttributesEnum.CodigoNumero.index();
    public static final int NOMBRE = AttributesEnum.Nombre.index();
    public static final int DESCRIPCION = AttributesEnum.Descripcion.index();
    public static final int ORDEN = AttributesEnum.Orden.index();
    public static final int ESTADO = AttributesEnum.Estado.index();
    public static final int USUARIO = AttributesEnum.Usuario.index();
    public static final int USUARIOFECHA = AttributesEnum.UsuarioFecha.index();
    public static final int USUARIOPROGRAMA = AttributesEnum.UsuarioPrograma.index();
    public static final int MODULO = AttributesEnum.Modulo.index();
    public static final int CODIGOTEXTOCODIGODEFINIDOUSUARIO = AttributesEnum.CodigoTextoCodigoDefinidoUsuario.index();
    public static final int GRUPOCODIGODEFINIDOUSUARIO = AttributesEnum.GrupoCodigoDefinidoUsuario.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CodigoDefinidoUsuarioImpl() {
        super();
    }

    /**
     * @param idCodigoDefinidoUsuario key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer idCodigoDefinidoUsuario) {
        return new Key(new Object[] { idCodigoDefinidoUsuario });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("modelAdministrativo.bc.entidad.CodigoDefinidoUsuario");
    }


    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_DELETE)
            noBorrar(CODIGOTEXTOCODIGODEFINIDOUSUARIO);
        
        super.doDML(operation, e);
        //Id refresh
        if (operation == DML_INSERT)
            setAttribute(IDCODIGODEFINIDOUSUARIO, getUltimoId());        
    }
}

