package modelAdministrativo.bc.entidad;

import model.bc.Entidad;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 17 18:18:09 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RolImpl extends Entidad {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdRol,
        Nombre,
        Tipo,
        Estado,
        Usuario,
        UsuarioFecha,
        UsuarioPrograma,
        RolUsuario,
        Permiso;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDROL = AttributesEnum.IdRol.index();
    public static final int NOMBRE = AttributesEnum.Nombre.index();
    public static final int TIPO = AttributesEnum.Tipo.index();
    public static final int ESTADO = AttributesEnum.Estado.index();
    public static final int USUARIO = AttributesEnum.Usuario.index();
    public static final int USUARIOFECHA = AttributesEnum.UsuarioFecha.index();
    public static final int USUARIOPROGRAMA = AttributesEnum.UsuarioPrograma.index();
    public static final int ROLUSUARIO = AttributesEnum.RolUsuario.index();
    public static final int PERMISO = AttributesEnum.Permiso.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RolImpl() {
        super();
    }

    /**
     * @param idRol key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer idRol) {
        return new Key(new Object[] { idRol });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("modelAdministrativo.bc.entidad.Rol");
    }


    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_DELETE)            
            noBorrar(ROLUSUARIO, PERMISO);
        
        super.doDML(operation, e);
        //Id refresh
        if (operation == DML_INSERT)
            setAttribute(IDROL, getUltimoId());       
        
    }
}

