package modelAdministrativo.bc.vista.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 29 15:55:36 ECT 2021
// ---------------------------------------------------------------------
public interface CodigoDefinidoUsuarioDetalleView extends ViewObject {
    void cduAbajo();

    void cduArriba();

    void cduPrimero();

    void cduUltimo();
}

