package modelAdministrativo.bc.vista.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 25 11:33:16 ECT 2021
// ---------------------------------------------------------------------
public interface CodigoDefinidoUsuarioEncabezadoView extends ViewObject {
    void ejecutarIdEntidad(Integer id);


    void cduAbajo();

    void cduArriba();

    void cduPrimero();

    void cduUltimo();
}

