package modelAdministrativo.bc.vista.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 08 12:36:44 ECT 2021
// ---------------------------------------------------------------------
public interface MenuView extends ViewObject {
    void ejecutarIdEntidad(Integer id);

    void cduAbajo();

    void cduArriba();

    void cduPrimero();

    void cduUltimo();
}

