package modelAdministrativo.bc.vista.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 30 11:49:54 ECT 2021
// ---------------------------------------------------------------------
public interface RolView extends ViewObject {
    void ejecutarIdEntidad(Integer id);
}

