package modelAdministrativo.bc.vista.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 29 22:03:16 ECT 2021
// ---------------------------------------------------------------------
public interface UsuarioView extends ViewObject {
    void ejecutarIdEntidad(Integer id);
}

