package model.bc.vistaNoDML;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 16 13:35:38 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ModuloViewNoDMLRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdModulo,
        Indice,
        Nombre,
        Contexto,
        Usuario,
        UsuarioFecha,
        UsuarioPrograma,
        Estado,
        ParametroView,
        CodigoDefinidoUsuarioView;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDMODULO = AttributesEnum.IdModulo.index();
    public static final int INDICE = AttributesEnum.Indice.index();
    public static final int NOMBRE = AttributesEnum.Nombre.index();
    public static final int CONTEXTO = AttributesEnum.Contexto.index();
    public static final int USUARIO = AttributesEnum.Usuario.index();
    public static final int USUARIOFECHA = AttributesEnum.UsuarioFecha.index();
    public static final int USUARIOPROGRAMA = AttributesEnum.UsuarioPrograma.index();
    public static final int ESTADO = AttributesEnum.Estado.index();
    public static final int PARAMETROVIEW = AttributesEnum.ParametroView.index();
    public static final int CODIGODEFINIDOUSUARIOVIEW = AttributesEnum.CodigoDefinidoUsuarioView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ModuloViewNoDMLRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute IdModulo.
     * @return the IdModulo
     */
    public Integer getIdModulo() {
        return (Integer) getAttributeInternal(IDMODULO);
    }

    /**
     * Gets the attribute value for the calculated attribute Indice.
     * @return the Indice
     */
    public String getIndice() {
        return (String) getAttributeInternal(INDICE);
    }

    /**
     * Gets the attribute value for the calculated attribute Nombre.
     * @return the Nombre
     */
    public String getNombre() {
        return (String) getAttributeInternal(NOMBRE);
    }

    /**
     * Gets the attribute value for the calculated attribute Contexto.
     * @return the Contexto
     */
    public String getContexto() {
        return (String) getAttributeInternal(CONTEXTO);
    }

    /**
     * Gets the attribute value for the calculated attribute Usuario.
     * @return the Usuario
     */
    public String getUsuario() {
        return (String) getAttributeInternal(USUARIO);
    }

    /**
     * Gets the attribute value for the calculated attribute UsuarioFecha.
     * @return the UsuarioFecha
     */
    public Timestamp getUsuarioFecha() {
        return (Timestamp) getAttributeInternal(USUARIOFECHA);
    }

    /**
     * Gets the attribute value for the calculated attribute UsuarioPrograma.
     * @return the UsuarioPrograma
     */
    public String getUsuarioPrograma() {
        return (String) getAttributeInternal(USUARIOPROGRAMA);
    }

    /**
     * Gets the attribute value for the calculated attribute Estado.
     * @return the Estado
     */
    public String getEstado() {
        return (String) getAttributeInternal(ESTADO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ParametroView.
     */
    public RowIterator getParametroView() {
        return (RowIterator) getAttributeInternal(PARAMETROVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CodigoDefinidoUsuarioView.
     */
    public RowIterator getCodigoDefinidoUsuarioView() {
        return (RowIterator) getAttributeInternal(CODIGODEFINIDOUSUARIOVIEW);
    }
}

