package model.bc.vistaNoDML;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 16 13:34:31 ECT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ParametroViewNoDMLRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdParametro,
        IdModulo,
        Indice,
        Clave,
        Nombre,
        Descripcion,
        ValorTexto01,
        ValorTexto02,
        ValorNumero01,
        ValorNumero02,
        DefaultTexto01,
        DefaultTexto02,
        DefaultNumero01,
        DefaultNumero02,
        Usuario,
        UsuarioFecha,
        UsuarioPrograma;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDPARAMETRO = AttributesEnum.IdParametro.index();
    public static final int IDMODULO = AttributesEnum.IdModulo.index();
    public static final int INDICE = AttributesEnum.Indice.index();
    public static final int CLAVE = AttributesEnum.Clave.index();
    public static final int NOMBRE = AttributesEnum.Nombre.index();
    public static final int DESCRIPCION = AttributesEnum.Descripcion.index();
    public static final int VALORTEXTO01 = AttributesEnum.ValorTexto01.index();
    public static final int VALORTEXTO02 = AttributesEnum.ValorTexto02.index();
    public static final int VALORNUMERO01 = AttributesEnum.ValorNumero01.index();
    public static final int VALORNUMERO02 = AttributesEnum.ValorNumero02.index();
    public static final int DEFAULTTEXTO01 = AttributesEnum.DefaultTexto01.index();
    public static final int DEFAULTTEXTO02 = AttributesEnum.DefaultTexto02.index();
    public static final int DEFAULTNUMERO01 = AttributesEnum.DefaultNumero01.index();
    public static final int DEFAULTNUMERO02 = AttributesEnum.DefaultNumero02.index();
    public static final int USUARIO = AttributesEnum.Usuario.index();
    public static final int USUARIOFECHA = AttributesEnum.UsuarioFecha.index();
    public static final int USUARIOPROGRAMA = AttributesEnum.UsuarioPrograma.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ParametroViewNoDMLRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute IdParametro.
     * @return the IdParametro
     */
    public Integer getIdParametro() {
        return (Integer) getAttributeInternal(IDPARAMETRO);
    }

    /**
     * Gets the attribute value for the calculated attribute IdModulo.
     * @return the IdModulo
     */
    public Integer getIdModulo() {
        return (Integer) getAttributeInternal(IDMODULO);
    }

    /**
     * Gets the attribute value for the calculated attribute Indice.
     * @return the Indice
     */
    public String getIndice() {
        return (String) getAttributeInternal(INDICE);
    }

    /**
     * Gets the attribute value for the calculated attribute Clave.
     * @return the Clave
     */
    public String getClave() {
        return (String) getAttributeInternal(CLAVE);
    }

    /**
     * Gets the attribute value for the calculated attribute Nombre.
     * @return the Nombre
     */
    public String getNombre() {
        return (String) getAttributeInternal(NOMBRE);
    }

    /**
     * Gets the attribute value for the calculated attribute Descripcion.
     * @return the Descripcion
     */
    public String getDescripcion() {
        return (String) getAttributeInternal(DESCRIPCION);
    }

    /**
     * Gets the attribute value for the calculated attribute ValorTexto01.
     * @return the ValorTexto01
     */
    public String getValorTexto01() {
        return (String) getAttributeInternal(VALORTEXTO01);
    }

    /**
     * Gets the attribute value for the calculated attribute ValorTexto02.
     * @return the ValorTexto02
     */
    public String getValorTexto02() {
        return (String) getAttributeInternal(VALORTEXTO02);
    }

    /**
     * Gets the attribute value for the calculated attribute ValorNumero01.
     * @return the ValorNumero01
     */
    public BigDecimal getValorNumero01() {
        return (BigDecimal) getAttributeInternal(VALORNUMERO01);
    }

    /**
     * Gets the attribute value for the calculated attribute ValorNumero02.
     * @return the ValorNumero02
     */
    public BigDecimal getValorNumero02() {
        return (BigDecimal) getAttributeInternal(VALORNUMERO02);
    }

    /**
     * Gets the attribute value for the calculated attribute DefaultTexto01.
     * @return the DefaultTexto01
     */
    public String getDefaultTexto01() {
        return (String) getAttributeInternal(DEFAULTTEXTO01);
    }

    /**
     * Gets the attribute value for the calculated attribute DefaultTexto02.
     * @return the DefaultTexto02
     */
    public String getDefaultTexto02() {
        return (String) getAttributeInternal(DEFAULTTEXTO02);
    }

    /**
     * Gets the attribute value for the calculated attribute DefaultNumero01.
     * @return the DefaultNumero01
     */
    public BigDecimal getDefaultNumero01() {
        return (BigDecimal) getAttributeInternal(DEFAULTNUMERO01);
    }

    /**
     * Gets the attribute value for the calculated attribute DefaultNumero02.
     * @return the DefaultNumero02
     */
    public BigDecimal getDefaultNumero02() {
        return (BigDecimal) getAttributeInternal(DEFAULTNUMERO02);
    }

    /**
     * Gets the attribute value for the calculated attribute Usuario.
     * @return the Usuario
     */
    public String getUsuario() {
        return (String) getAttributeInternal(USUARIO);
    }

    /**
     * Gets the attribute value for the calculated attribute UsuarioFecha.
     * @return the UsuarioFecha
     */
    public Timestamp getUsuarioFecha() {
        return (Timestamp) getAttributeInternal(USUARIOFECHA);
    }

    /**
     * Gets the attribute value for the calculated attribute UsuarioPrograma.
     * @return the UsuarioPrograma
     */
    public String getUsuarioPrograma() {
        return (String) getAttributeInternal(USUARIOPROGRAMA);
    }
}

